import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/mouse-memoirs"; 
import "@fontsource/montserrat"; // Defaults to weight 400
import "@fontsource/montserrat/300.css";
import "@fontsource/montserrat/400.css";
import "@fontsource/montserrat/500.css";
import "@fontsource/montserrat/600.css";
import "@fontsource/montserrat/700.css";
import "@fontsource/montserrat/700.css";
import "@fontsource/montserrat/900.css";
export const metadata: Metadata = {
  title: "Inicio - La Chacra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className="overflor-hidden"
      >
        {children}
      </body>
    </html>
  );
}
